// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoV4zmS_xmKaV5RyunZQLSVaKTS9pKp_w',
    appId: '1:400952145454:web:9a38cf433addd7fb7d11bf',
    messagingSenderId: '400952145454',
    projectId: 'hasta-tkp',
    authDomain: 'hasta-tkp.firebaseapp.com',
    databaseURL: 'https://hasta-tkp.firebaseio.com',
    storageBucket: 'hasta-tkp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNYz6arR_na3LCETl2Jv9IcOzbxC66lJ8',
    appId: '1:400952145454:android:c394b2e29a2089c17d11bf',
    messagingSenderId: '400952145454',
    projectId: 'hasta-tkp',
    databaseURL: 'https://hasta-tkp.firebaseio.com',
    storageBucket: 'hasta-tkp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1EPATJH7ubDq6JkI9vQ15u9Uj9yMNSyI',
    appId: '1:400952145454:ios:4517993a72079dd17d11bf',
    messagingSenderId: '400952145454',
    projectId: 'hasta-tkp',
    databaseURL: 'https://hasta-tkp.firebaseio.com',
    storageBucket: 'hasta-tkp.firebasestorage.app',
    iosBundleId: 'com.dentamed.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1EPATJH7ubDq6JkI9vQ15u9Uj9yMNSyI',
    appId: '1:400952145454:ios:4517993a72079dd17d11bf',
    messagingSenderId: '400952145454',
    projectId: 'hasta-tkp',
    databaseURL: 'https://hasta-tkp.firebaseio.com',
    storageBucket: 'hasta-tkp.firebasestorage.app',
    iosBundleId: 'com.dentamed.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg6PmIAyr1jAag5EMt68VEoPBHCmBB0uo',
    appId: '1:400952145454:web:1226fd017e30aa1b7d11bf',
    messagingSenderId: '400952145454',
    projectId: 'hasta-tkp',
    authDomain: 'hasta-tkp.firebaseapp.com',
    databaseURL: 'https://hasta-tkp.firebaseio.com',
    storageBucket: 'hasta-tkp.firebasestorage.app',
  );
}
